ALTER TABLE "researcher_profiles" ADD COLUMN IF NOT EXISTS "disciplines" jsonb DEFAULT '[]'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "researcher_profiles" ADD COLUMN IF NOT EXISTS "discipline_other" text;--> statement-breakpoint
ALTER TABLE "researcher_profiles" ADD COLUMN IF NOT EXISTS "research_area_other" text;
--> statement-breakpoint
-- Research areas for the discipline picker in src/lib/disciplines.ts.
-- Idempotent, and an existing row with the same slug is reused rather than renamed.
INSERT INTO research_fields (name, slug) VALUES
  ('Aging & Gerontology', 'aging-gerontology'),
  ('Anesthesiology', 'anesthesiology'),
  ('Cardiology & Cardiovascular Health', 'cardiology-cardiovascular-health'),
  ('Clinical Epidemiology', 'clinical-epidemiology'),
  ('Clinical Research', 'clinical-research'),
  ('Critical Care', 'critical-care'),
  ('Dentistry & Oral Health', 'dentistry-oral-health'),
  ('Dermatology', 'dermatology'),
  ('Digital Health', 'digital-health'),
  ('Emergency Medicine', 'emergency-medicine'),
  ('Endocrinology & Metabolism', 'endocrinology-metabolism'),
  ('Family Medicine', 'family-medicine'),
  ('Gastroenterology', 'gastroenterology'),
  ('Global Health', 'global-health'),
  ('Health Informatics', 'health-informatics'),
  ('Health Policy', 'health-policy'),
  ('Health Services Research', 'health-services-research'),
  ('Hematology', 'hematology'),
  ('Infectious Diseases', 'infectious-diseases'),
  ('Medical Education', 'medical-education'),
  ('Medical Imaging & Radiology', 'medical-imaging-radiology'),
  ('Mental Health & Psychiatry', 'mental-health-psychiatry'),
  ('Musculoskeletal Health', 'musculoskeletal-health'),
  ('Nephrology', 'nephrology'),
  ('Neurology', 'neurology'),
  ('Nursing', 'nursing'),
  ('Nutrition', 'nutrition'),
  ('Obstetrics & Gynecology', 'obstetrics-gynecology'),
  ('Occupational Health', 'occupational-health'),
  ('Oncology & Cancer Research', 'oncology-cancer-research'),
  ('Ophthalmology', 'ophthalmology'),
  ('Orthopaedics', 'orthopaedics'),
  ('Otolaryngology', 'otolaryngology'),
  ('Pain & Pain Management', 'pain-pain-management'),
  ('Palliative Care', 'palliative-care'),
  ('Pathology', 'pathology'),
  ('Pediatrics', 'pediatrics'),
  ('Pharmacy', 'pharmacy'),
  ('Physical Medicine & Rehabilitation', 'physical-medicine-rehabilitation'),
  ('Physiotherapy', 'physiotherapy'),
  ('Population Health', 'population-health'),
  ('Primary Care', 'primary-care'),
  ('Public Health', 'public-health'),
  ('Rehabilitation Sciences', 'rehabilitation-sciences'),
  ('Reproductive Health', 'reproductive-health'),
  ('Respirology', 'respirology'),
  ('Rheumatology', 'rheumatology'),
  ('Surgery', 'surgery'),
  ('Transplantation', 'transplantation'),
  ('Urology', 'urology'),
  ('Women’s Health', 'womens-health'),
  ('Anatomy', 'anatomy'),
  ('Biochemistry', 'biochemistry'),
  ('Bioinformatics', 'bioinformatics'),
  ('Biophysics', 'biophysics'),
  ('Biotechnology', 'biotechnology'),
  ('Botany & Plant Science', 'botany-plant-science'),
  ('Cell Biology', 'cell-biology'),
  ('Computational Biology', 'computational-biology'),
  ('Developmental Biology', 'developmental-biology'),
  ('Ecology', 'ecology'),
  ('Evolutionary Biology', 'evolutionary-biology'),
  ('Genetics', 'genetics'),
  ('Genomics', 'genomics'),
  ('Immunology', 'immunology'),
  ('Marine Biology', 'marine-biology'),
  ('Microbiology', 'microbiology'),
  ('Molecular Biology', 'molecular-biology'),
  ('Molecular Genetics', 'molecular-genetics'),
  ('Neuroscience', 'neuroscience'),
  ('Pharmacology', 'pharmacology'),
  ('Physiology', 'physiology'),
  ('Proteomics', 'proteomics'),
  ('Stem Cell Biology', 'stem-cell-biology'),
  ('Structural Biology', 'structural-biology'),
  ('Systems Biology', 'systems-biology'),
  ('Virology', 'virology'),
  ('Zoology', 'zoology'),
  ('Behavioural Science', 'behavioural-science'),
  ('Clinical Psychology', 'clinical-psychology'),
  ('Cognitive Psychology', 'cognitive-psychology'),
  ('Developmental Psychology', 'developmental-psychology'),
  ('Educational Psychology', 'educational-psychology'),
  ('Health Psychology', 'health-psychology'),
  ('Industrial & Organizational Psychology', 'industrial-organizational-psychology'),
  ('Neuropsychology', 'neuropsychology'),
  ('Personality Psychology', 'personality-psychology'),
  ('Positive Psychology', 'positive-psychology'),
  ('Quantitative Psychology', 'quantitative-psychology'),
  ('Social Psychology', 'social-psychology'),
  ('Aerospace Engineering', 'aerospace-engineering'),
  ('Biomedical Engineering', 'biomedical-engineering'),
  ('Chemical Engineering', 'chemical-engineering'),
  ('Civil Engineering', 'civil-engineering'),
  ('Computer Engineering', 'computer-engineering'),
  ('Electrical Engineering', 'electrical-engineering'),
  ('Environmental Engineering', 'environmental-engineering'),
  ('Industrial Engineering', 'industrial-engineering'),
  ('Materials Engineering', 'materials-engineering'),
  ('Mechanical Engineering', 'mechanical-engineering'),
  ('Mechatronics', 'mechatronics'),
  ('Nuclear Engineering', 'nuclear-engineering'),
  ('Robotics', 'robotics'),
  ('Software Engineering', 'software-engineering'),
  ('Systems Engineering', 'systems-engineering'),
  ('Artificial Intelligence', 'artificial-intelligence'),
  ('Computer Graphics', 'computer-graphics'),
  ('Computer Vision', 'computer-vision'),
  ('Cybersecurity', 'cybersecurity'),
  ('Data Science', 'data-science'),
  ('Databases & Information Systems', 'databases-information-systems'),
  ('Human-Computer Interaction', 'human-computer-interaction'),
  ('Machine Learning', 'machine-learning'),
  ('Natural Language Processing', 'natural-language-processing'),
  ('Networks & Distributed Systems', 'networks-distributed-systems'),
  ('Software Systems', 'software-systems'),
  ('Theoretical Computer Science', 'theoretical-computer-science'),
  ('Analytical Chemistry', 'analytical-chemistry'),
  ('Chemical Biology', 'chemical-biology'),
  ('Computational Chemistry', 'computational-chemistry'),
  ('Inorganic Chemistry', 'inorganic-chemistry'),
  ('Materials Chemistry', 'materials-chemistry'),
  ('Materials Science', 'materials-science'),
  ('Medicinal Chemistry', 'medicinal-chemistry'),
  ('Nanotechnology', 'nanotechnology'),
  ('Organic Chemistry', 'organic-chemistry'),
  ('Physical Chemistry', 'physical-chemistry'),
  ('Polymer Science', 'polymer-science'),
  ('Applied Physics', 'applied-physics'),
  ('Astrophysics', 'astrophysics'),
  ('Atomic, Molecular & Optical Physics', 'atomic-molecular-optical-physics'),
  ('Condensed Matter Physics', 'condensed-matter-physics'),
  ('Cosmology', 'cosmology'),
  ('Medical Physics', 'medical-physics'),
  ('Nuclear Physics', 'nuclear-physics'),
  ('Particle Physics', 'particle-physics'),
  ('Quantum Science', 'quantum-science'),
  ('Theoretical Physics', 'theoretical-physics'),
  ('Applied Mathematics', 'applied-mathematics'),
  ('Biostatistics', 'biostatistics'),
  ('Computational Mathematics', 'computational-mathematics'),
  ('Mathematical Biology', 'mathematical-biology'),
  ('Mathematical Modelling', 'mathematical-modelling'),
  ('Probability', 'probability'),
  ('Pure Mathematics', 'pure-mathematics'),
  ('Statistics', 'statistics'),
  ('Accounting', 'accounting'),
  ('Business Analytics', 'business-analytics'),
  ('Consumer Behaviour', 'consumer-behaviour'),
  ('Entrepreneurship', 'entrepreneurship'),
  ('Finance', 'finance'),
  ('Human Resources', 'human-resources'),
  ('Innovation', 'innovation'),
  ('International Business', 'international-business'),
  ('Leadership', 'leadership'),
  ('Management', 'management'),
  ('Marketing', 'marketing'),
  ('Operations Management', 'operations-management'),
  ('Organizational Behaviour', 'organizational-behaviour'),
  ('Strategy', 'strategy'),
  ('Supply Chain Management', 'supply-chain-management'),
  ('Applied Economics', 'applied-economics'),
  ('Behavioural Economics', 'behavioural-economics'),
  ('Development Economics', 'development-economics'),
  ('Econometrics', 'econometrics'),
  ('Environmental Economics', 'environmental-economics'),
  ('Financial Economics', 'financial-economics'),
  ('Health Economics', 'health-economics'),
  ('International Economics', 'international-economics'),
  ('Labour Economics', 'labour-economics'),
  ('Macroeconomics', 'macroeconomics'),
  ('Microeconomics', 'microeconomics'),
  ('Public Economics', 'public-economics'),
  ('Anthropology', 'anthropology'),
  ('Criminology', 'criminology'),
  ('Demography', 'demography'),
  ('Development Studies', 'development-studies'),
  ('Gender & Sexuality Studies', 'gender-sexuality-studies'),
  ('Geography', 'geography'),
  ('International Relations', 'international-relations'),
  ('Political Science', 'political-science'),
  ('Public Administration', 'public-administration'),
  ('Public Policy', 'public-policy'),
  ('Social Policy', 'social-policy'),
  ('Social Work', 'social-work'),
  ('Sociology', 'sociology'),
  ('Urban Studies', 'urban-studies'),
  ('Curriculum & Instruction', 'curriculum-instruction'),
  ('Education Policy', 'education-policy'),
  ('Educational Leadership', 'educational-leadership'),
  ('Educational Technology', 'educational-technology'),
  ('Higher Education', 'higher-education'),
  ('Learning Sciences', 'learning-sciences'),
  ('Special Education', 'special-education'),
  ('Teaching & Pedagogy', 'teaching-pedagogy'),
  ('Classics', 'classics'),
  ('Cultural Studies', 'cultural-studies'),
  ('Ethics', 'ethics'),
  ('History', 'history'),
  ('Languages', 'languages'),
  ('Linguistics', 'linguistics'),
  ('Literature', 'literature'),
  ('Philosophy', 'philosophy'),
  ('Religious Studies', 'religious-studies'),
  ('Business & Corporate Law', 'business-corporate-law'),
  ('Constitutional Law', 'constitutional-law'),
  ('Criminal Law', 'criminal-law'),
  ('Environmental Law', 'environmental-law'),
  ('Health Law', 'health-law'),
  ('Human Rights Law', 'human-rights-law'),
  ('Intellectual Property Law', 'intellectual-property-law'),
  ('International Law', 'international-law'),
  ('Labour & Employment Law', 'labour-employment-law'),
  ('Technology, Data & Privacy Law', 'technology-data-privacy-law'),
  ('Agriculture', 'agriculture'),
  ('Atmospheric Science', 'atmospheric-science'),
  ('Climate Change', 'climate-change'),
  ('Conservation Biology', 'conservation-biology'),
  ('Earth Sciences', 'earth-sciences'),
  ('Environmental Science', 'environmental-science'),
  ('Environmental Sustainability', 'environmental-sustainability'),
  ('Forestry', 'forestry'),
  ('Geology', 'geology'),
  ('Hydrology', 'hydrology'),
  ('Oceanography', 'oceanography'),
  ('Renewable Energy', 'renewable-energy'),
  ('Sustainability', 'sustainability'),
  ('Communication Studies', 'communication-studies'),
  ('Digital Media', 'digital-media'),
  ('Film & Media Studies', 'film-media-studies'),
  ('Journalism', 'journalism'),
  ('Media Studies', 'media-studies'),
  ('Music', 'music'),
  ('Performing Arts', 'performing-arts'),
  ('Visual Arts', 'visual-arts'),
  ('Bioethics', 'bioethics'),
  ('Computational Social Science', 'computational-social-science'),
  ('Equity, Diversity & Inclusion', 'equity-diversity-inclusion'),
  ('Implementation Science', 'implementation-science'),
  ('Indigenous Studies', 'indigenous-studies'),
  ('Knowledge Translation', 'knowledge-translation'),
  ('One Health', 'one-health'),
  ('Science & Technology Studies', 'science-technology-studies'),
  ('Translational Research', 'translational-research')
ON CONFLICT (slug) DO NOTHING;
